「PyTorchとは？」
===============================================================
【原題】What is PyTorch?

【原著】[Soumith Chintala](http://soumith.ch/)

【元URL】https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

【翻訳】電通国際情報サービスISID AIトランスフォーメーションセンター　徳原 光

【日付】2020年10月13日

【チュトーリアル概要】

本チュートリアルでは、PyTorchでの演算処理に用いるTorch Tensorについて、その操作方法を解説します。

---



PyTorchとは？
================

PyTorchはPythonをベースとした科学計算ライブラリです。

PyTorchは以下に示す2つの機能を使用したいユーザーを対象としています。

- Numpyベースの演算の代わりに、GPUを用いた高速な演算の実施
- 高い柔軟性と実行速度を有したディープラーニングのプラットフォーム




Tensors（テンソル）
-------------

TensorはNumPy ndarraysのような多次元配列です。

PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能です。

In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function # print functionをprint()で実行できる様にするもの（多分）
import torch

【注意】

初期化されていない行列が宣言・作成されても、実際に使用されるまで明確な値は保有していません。

宣言時にメモリ上の割り当てられた適当な値が初期値として入っています。

## 学習したこと
- torch.empty(): メモリ（主にヒープ領域）の初期化をスキップ（値を指定せずにそのヒープ領域にあったものを設定）するため、以前のデータの残骸が初期値として入る。

- 速度のメリット: 0で埋める時間を省けるため、巨大なテンソルを扱う際の高速化に役立つ。

- セキュリティ面: OSの保護機能により、他のアプリのデータが混じることはない。ただし、同じプログラム内で直前に扱った重要データの残骸が残っている可能性はあるため、機密情報を扱う際は注意が必要。




初期化されていない、3×5行列を生成してみましょう：



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.9002e+35,  4.4097e-41, -9.3532e-29],
        [ 4.4097e-41,  1.8998e+35,  4.4097e-41],
        [ 1.9162e+35,  4.4097e-41,  1.8994e+35],
        [ 4.4097e-41,  1.9245e+35,  4.4097e-41],
        [ 1.9245e+35,  4.4097e-41,  1.6385e-38]])


次に、乱数によって初期化された3x5行列を生成してみましょう:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2272, 0.9243, 0.8820],
        [0.1184, 0.3525, 0.3530],
        [0.7430, 0.5133, 0.3812],
        [0.8721, 0.8605, 0.6744],
        [0.8976, 0.8415, 0.4257]])


long型の数値0で初期化された行列を生成する場合は次の通りです。



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接、数値を指定して行列を生成することもできます。



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


その他に、すでにあるtensorをもとに、新しくtensorを生成することもできます。

本メソッドで生成したテンソルは、テンソルの特性（例えばデータ型：dtypeなど）を、もとのtensorから引き継ぎます（ユーザーが値や特性を直接上書きしない限り）。

## 学習したこと
- torch.tandn_like()は正規分布に従うランダムな値（平均0、分散1）

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes, double = float64
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6904,  0.1597,  0.9425],
        [ 1.2191, -0.1138, -1.2284],
        [ 1.6409, -2.1874,  1.5138],
        [ 0.6348,  1.4080, -1.1242],
        [-1.1203, -0.8740,  2.2569]])


テンソルサイズ（size）≒テンソルの形、を求めてみます。



In [8]:
print(x.size())

torch.Size([5, 3])


【メモ】

``torch.Size``はタプルとなっているため、Pythonの通常のタプルと同様の操作が可能です。

**テンソルの操作（変形・変換等）**


PyTorchにはテンソルに対する操作（変形・変換等）が多く用意されています。

ここで、tensorを操作（変形・変換等）する追加の例を紹介します。



補足: 用例1

In [9]:
y = torch.rand(5, 3)

print(x)
print(y)
print(x + y)

tensor([[ 0.6904,  0.1597,  0.9425],
        [ 1.2191, -0.1138, -1.2284],
        [ 1.6409, -2.1874,  1.5138],
        [ 0.6348,  1.4080, -1.1242],
        [-1.1203, -0.8740,  2.2569]])
tensor([[0.3564, 0.8112, 0.5291],
        [0.9028, 0.8592, 0.8455],
        [0.6325, 0.0029, 0.4626],
        [0.5171, 0.8550, 0.2448],
        [0.9091, 0.4038, 0.0426]])
tensor([[ 1.0468,  0.9709,  1.4717],
        [ 2.1219,  0.7454, -0.3830],
        [ 2.2733, -2.1845,  1.9765],
        [ 1.1519,  2.2630, -0.8794],
        [-0.2112, -0.4703,  2.2995]])


補足: 用例2



In [10]:
print(torch.add(x, y))

tensor([[ 1.0468,  0.9709,  1.4717],
        [ 2.1219,  0.7454, -0.3830],
        [ 2.2733, -2.1845,  1.9765],
        [ 1.1519,  2.2630, -0.8794],
        [-0.2112, -0.4703,  2.2995]])


補足: 出力先を引数で指定



In [11]:
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[1.8946e-04, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 8.9683e-44, 0.0000e+00],
        [1.5695e-43, 0.0000e+00, 3.3163e-40],
        [0.0000e+00, 0.0000e+00, 1.4013e-45],
        [3.8047e-04, 0.0000e+00, 4.7190e+34]])
tensor([[ 1.0468,  0.9709,  1.4717],
        [ 2.1219,  0.7454, -0.3830],
        [ 2.2733, -2.1845,  1.9765],
        [ 1.1519,  2.2630, -0.8794],
        [-0.2112, -0.4703,  2.2995]])


補足：テンソルそのものの変更（in-place：インプレース処理）



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0468,  0.9709,  1.4717],
        [ 2.1219,  0.7454, -0.3830],
        [ 2.2733, -2.1845,  1.9765],
        [ 1.1519,  2.2630, -0.8794],
        [-0.2112, -0.4703,  2.2995]])


【メモ】

メソッド名の後に``_``をつけることで、変数の内容を出力結果で置き換えることができます。

例えば、``y.add_(x)``の場合xとyの値を加算した結果はyに上書きして、格納されます。

NumPyと同様、インデクシングやスライシングを行うことも可能です。

In [13]:
print(x)

print(x[:, 1])

tensor([[ 0.6904,  0.1597,  0.9425],
        [ 1.2191, -0.1138, -1.2284],
        [ 1.6409, -2.1874,  1.5138],
        [ 0.6348,  1.4080, -1.1242],
        [-1.1203, -0.8740,  2.2569]])
tensor([ 0.1597, -0.1138, -2.1874,  1.4080, -0.8740])


リサイズ: tensorの形を変えたい場合は ``torch.view``を使用してください:



In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  -1を指定すると他に設定した次元の値から自動で計算
print(x.size(), y.size(), z.size())

print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.8282, -0.2900,  0.5625, -0.3602],
        [ 1.2836,  0.8853, -0.4329,  0.1597],
        [-2.4105,  0.0621,  2.2360,  0.4317],
        [ 1.2870,  0.4183, -0.8491,  2.6742]])
tensor([-0.8282, -0.2900,  0.5625, -0.3602,  1.2836,  0.8853, -0.4329,  0.1597,
        -2.4105,  0.0621,  2.2360,  0.4317,  1.2870,  0.4183, -0.8491,  2.6742])
tensor([[-0.8282, -0.2900,  0.5625, -0.3602,  1.2836,  0.8853, -0.4329,  0.1597],
        [-2.4105,  0.0621,  2.2360,  0.4317,  1.2870,  0.4183, -0.8491,  2.6742]])


``.item()``を使用すると、要素を1つしか持たないtensorから、中身の数値だけを取り出すことができます。


In [15]:
x = torch.randn(1)
print(x)
print(x.item())
print(type(x.item()))

tensor([-2.0191])
-2.0191023349761963
<class 'float'>


**参考:**

PyTorchでは、転置、インデックシング、スライシング、演算処理、線形代数、乱数生成などの100を超える機能が提供されています。

詳しくは[こちらのページ](https://pytorch.org/docs/stable/torch.html)をご覧ください。

NumPyとの接続
------------

PyTorchではTorch TensorからNumPy Arrayへの変換やその逆を簡単に行うことできます。

（Torch TensorがCPU上にある場合）Torch TensorとNumPy Arrayはメモリ上の同じ領域に配置され、変換することができます。



Torch Tensorから NumPy Arrayへの変換
--------




In [16]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [17]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


メモリを共有しているため、Torch Tensorの値がNumPy Arrayにも反映されることが分かります。



In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy ArrayからTorch Tensorへの変換
---------

NumPy ArrayからTorch Tensorへの変換も、容易に可能です。



In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensorを除き、CPU上のすべてのTensorはNumPyへの変換、およびその逆（NumpyからTensor）に対応しています。


CUDA Tensors（CUDA テンソル）
------------

tensorは ``.to`` メソッドを使用することであらゆるデバイス上のメモリへと移動させることができます。

In [26]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print("z device:", z.device)
    print(z)
    z_cpu = z.to("cpu", torch.double) # 破壊的ではないので、zはcudaのまま
    print(z_cpu)
    print(z_cpu.device)       # ``.to`` can also change dtype together!


# 日本語訳注：
# tensor([1.8299], device='cuda:0')
# tensor([1.8299], dtype=torch.float64)
# のような出力（値は変わります）がセルのあとに表示されれば、GPUでのCUDAでのテンソル計算が成功しています。
# もし、何も表示されなければ、Google ColaroboratoryがGPU使用モードになっていないので、
# 下のセルの説明を読んで、GPUを使用可能な状態にしてみてください。

z device: cuda:0
tensor([-1.0191], device='cuda:0')
tensor([-1.0191], dtype=torch.float64)
cpu


（日本語訳注）

Google ColaboratoryでCUDA、すなわちGPUを使用可能にするには、上部メニューの「ランタイム」を選択し、「ランタイムのタイプを変更」で、「ハードウェア アクセラレータ」にGPUを選択します。


上記で、現在のランタイムの環境を確認し、GPUでなければ、GPUに設定して、上記セルを実行してみてください。